### PR TITLE
Authentication - Add user setup

### LINKED ISSUE #8: [Feature] Set hostname, set first user and set root password.
A new screen is required where the user can insert a valid hostname to the new machine, the first user's username, the first user's password, and the root's password.

A double field with matching assertion is desired, but not required. Passwords shouldn't echo. It's recommended to use TextFields and present the input in at least three separate rows.

t's not necessary to create the user, set the password or set/write the hostname, as that will be appended to the setup script so the user can review it on later steps. So only keeping each field in memory is enough.

For layout/design inspirations, one can consult other screens, especially WifiMenu.

Estimated complexity: 100 lines of C code + 130 lines of QML.

Files that may be created:
 * `src/lib/users.hpp`
 * `src/lib/users.cpp`
 * `qml/UserSetup.qml`

Files that have to be modified:
 * `src/main.cpp`: Add include, instantiate new class, connect to a QML property.
 * `qml/MainContainer.qml`: Needs to instantiate the new component and assign an id to it.
 * `chaotic-installer.pro` Add new `cpp` and `hpp` to the build system.

### PR DESCRIPTION
**Pull request by vagrantsn**
## What does it do
This Pull Request adds the User setup step, which includes password and hostname settings.

## Checklist
- [x] Add field for user name
- [x] Add fields for user password and confirmation
- [x] Add fields for root password and confirmation
- [x] Add field for hostname
- [x] Add locales

## How to test
Proceed through the steps until the user setup or set the step to be the first one manually, changing:
https://github.com/PedroHLC/chaotic-installer-qt/blob/50b8c5a9541d277562f7bb16f394b20566918a43/qml/MainContainer.qml#L74
to:
```qml
initialItem: userSetup
```

Resolves #8

---
This change is [Reviewable](https://reviewable.io/reviews/pedrohlc/chaotic-installer-qt/11)

### CODE REVIEW

**Review by PedroHLC — CHANGES_REQUESTED** [review]
* [X] Confirmed it compiles and runs as expected.
* [X] Confirms it resolves #8 ([Feature] Set hostname, set first user and set root password.) 

Thanks for the contribution, your QML is very nice, and the C++ code is KISS enough. Liked the layout overall and how you even handled the translations.

I've left these two notes pending, I hope they're not inconvenient. When finished I'll merge it ASAP.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pedrohlc/chaotic-installer-qt/11#-:-Lr4mqxUDTJvuELHdRui:bopi3wb)* status: all files reviewed, 2 unresolved discussions (waiting on @vagnervst)

___
*[chaotic-installer.pro, line 20 at r1](https://reviewable.io/reviews/pedrohlc/chaotic-installer-qt/11#-Lr4khUf-9TFme8jRTHb:-Lr4khUgE3XCPgwWeMZh:bbjthe9) ([raw file](https://github.com/pedrohlc/chaotic-installer-qt/blob/2b9c4b050a003fd61764832c5ff758c3df374f51/chaotic-installer.pro#L20)):*
> ```QMake
> 	lib/network.cpp lib/mirrors.cpp \
> 	lib/locales.cpp \
> 	src/lib/user.cpp
> ```

Just a small manual adjust, as `src/` is already in `VPATH` it's not required in these paths (SOURCE and HEADERS).
___
*[src/lib/user.cpp, line 100 at r1](https://reviewable.io/reviews/pedrohlc/chaotic-installer-qt/11#-Lr4lxygEajom0af2Lzi:-Lr4lxyh795mZcaorWEH:bdvqp25) ([raw file](https://github.com/pedrohlc/chaotic-installer-qt/blob/2b9c4b050a003fd61764832c5ff758c3df374f51/src/lib/user.cpp#L100)):*
> ```cpp
>     setIsValid(true);
> 
>     validatePasswords(tr("User passwords don't match"), userPassword, userPasswordConfirm);
> ```

`tr`s are translatable, please run `lupdate -verbose -pro chaotic-installer.pro` to automatically append these on the source of the translations.
(My mistake, I forgot to add it to CONTRIBUTING.md)

**Review by vagrantsn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pedrohlc/chaotic-installer-qt/11)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @PedroHLC)

___
*[chaotic-installer.pro, line 20 at r1](https://reviewable.io/reviews/pedrohlc/chaotic-installer-qt/11#-Lr4khUf-9TFme8jRTHb:-Lr58JkL3u8ivU591bhk:b-896fja) ([raw file](https://github.com/pedrohlc/chaotic-installer-qt/blob/2b9c4b050a003fd61764832c5ff758c3df374f51/chaotic-installer.pro#L20)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

Just a small manual adjust, as `src/` is already in `VPATH` it's not required in these paths (SOURCE and HEADERS).
</blockquote></details>

Done!
___
*[src/lib/user.cpp, line 100 at r1](https://reviewable.io/reviews/pedrohlc/chaotic-installer-qt/11#-Lr4lxygEajom0af2Lzi:-Lr58MHPCLEUp3mdUVzq:b-tsh9kz) ([raw file](https://github.com/pedrohlc/chaotic-installer-qt/blob/2b9c4b050a003fd61764832c5ff758c3df374f51/src/lib/user.cpp#L100)):*
<details><summary><i>Previously, PedroHLC (Pedro) wrote…</i></summary><blockquote>

`tr`s are translatable, please run `lupdate -verbose -pro chaotic-installer.pro` to automatically append these on the source of the translations.
(My mistake, I forgot to add it to CONTRIBUTING.md)
</blockquote></details>

Done! I also took the time to add this to `CONTRIBUTING.md` :slightly_smiling_face:

**Comment by PedroHLC** [comment]
:lgtm_strong: 
Thanks for the contribution!

**Review by PedroHLC — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pedrohlc/chaotic-installer-qt/11#-:-Lr5GqIR70EMEe-R0q9Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
